# -*- coding: utf-8 -*-
"""Computer Vision Lab Sheet - 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kLF_DLZ5Mn-cF0zOy3FWzStalYgl3eqT

#### **Experiment No. 2**
#### **Experiment Name - Contrast Enhancement and Histogram-Based Image Processing using Python and OpenCV**

#### **Steps**

##### **NAME : Atul Krishna**
##### **COURSE : B.Tech CSE**
##### **SECTION - B**
##### **SUBJECT : Computer Vision**
##### **ROLL NO. : 14**
##### **CU ID : CU24250231**

##### **1. Import the required libraries, including OpenCV, NumPy, and Matplotlib.**
"""

# Importing required libraries
import cv2
import numpy as np
import matplotlib.pyplot as plt

print("Libraries imported successfully.")

"""##### **2. Load a low-contrast grayscale image or convert a color image into grayscale for processing.**"""

# Uploading and loading the image
from google.colab import files
uploaded = files.upload()

image_name = next(iter(uploaded))
img = cv2.imread(image_name, cv2.IMREAD_GRAYSCALE)

if img is None:
    print("Error: Image could not be loaded.")
else:
    print("Image loaded successfully.")
    print("Image dimensions:", img.shape)

"""##### **3. Display the original image and generate its histogram to analyze the distribution of pixel intensity values.**"""

# Displaying original image and its histogram
plt.figure(figsize=(5, 4))

plt.subplot(1, 2, 1)
plt.imshow(img, cmap='gray')
plt.title("Original Grayscale Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.hist(img.ravel(), bins=256, range=[0, 256])
plt.title("Histogram of Original Image")
plt.xlabel("Pixel Intensity")
plt.ylabel("Frequency")

plt.tight_layout()
plt.show()

"""##### **4. Perform contrast stretching to improve the dynamic range of pixel intensities.**"""

# Contrast Stretching
min_pixel = np.min(img)
max_pixel = np.max(img)

contrast_stretched = ((img - min_pixel) / (max_pixel - min_pixel) * 255).astype(np.uint8)

plt.figure(figsize=(5, 4))

plt.subplot(1, 2, 1)
plt.imshow(contrast_stretched, cmap='gray')
plt.title("Contrast Stretched Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.hist(contrast_stretched.ravel(), bins=256, range=[0, 256])
plt.title("Histogram After Contrast Stretching")
plt.xlabel("Pixel Intensity")
plt.ylabel("Frequency")

plt.tight_layout()
plt.show()

"""##### **5. Apply Histogram Equalization using OpenCV and compare the enhanced image with the original image.**"""

# Applying Histogram Equalization

hist_equalized = cv2.equalizeHist(img)
plt.figure(figsize=(5, 4))

plt.subplot(1, 2, 1)
plt.imshow(hist_equalized, cmap='gray')
plt.title("Histogram Equalized Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.hist(hist_equalized.ravel(), bins=256, range=[0, 256])
plt.title("Histogram After Equalization")
plt.xlabel("Pixel Intensity")
plt.ylabel("Frequency")

plt.tight_layout()
plt.show()

"""##### **6. Implement Contrast Limited Adaptive Histogram Equalization (CLAHE) and observe its performance on images with varying illumination.**"""

# Contrast Limited Adaptive Histogram Equalization (CLAHE)

clahe = cv2.createCLAHE(
    clipLimit=2.0,
    tileGridSize=(8, 8)
)

clahe_image = clahe.apply(img)
plt.figure(figsize=(5, 4))

plt.subplot(1, 2, 1)
plt.imshow(clahe_image, cmap='gray')
plt.title("CLAHE Enhanced Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.hist(clahe_image.ravel(), bins=256, range=[0, 256])
plt.title("Histogram After CLAHE")
plt.xlabel("Pixel Intensity")
plt.ylabel("Frequency")

plt.tight_layout()
plt.show()

"""##### **7. Plot and compare the histograms of the original, histogram-equalized, and CLAHEenhanced images.**"""

# Comparing histograms of original, equalized and CLAHE images

plt.figure(figsize=(5, 4))

plt.hist(
    img.ravel(),
    bins=256,
    range=[0, 256],
    alpha=0.5,
    label="Original"
)

plt.hist(
    hist_equalized.ravel(),
    bins=256,
    range=[0, 256],
    alpha=0.5,
    label="Histogram Equalization"
)

plt.hist(
    clahe_image.ravel(),
    bins=256,
    range=[0, 256],
    alpha=0.5,
    label="CLAHE"
)

plt.title("Comparison of Image Histograms")
plt.xlabel("Pixel Intensity")
plt.ylabel("Frequency")
plt.legend()

plt.show()

"""##### **8. Analyze the visual improvements in terms of brightness, contrast, and feature visibility.**"""

# Visual comparison of all enhancement techniques

plt.figure(figsize=(5, 4))

plt.subplot(2, 2, 1)
plt.imshow(img, cmap='gray')
plt.title("Original Image")
plt.axis("off")

plt.subplot(2, 2, 2)
plt.imshow(contrast_stretched, cmap='gray')
plt.title("Contrast Stretching")
plt.axis("off")

plt.subplot(2, 2, 3)
plt.imshow(hist_equalized, cmap='gray')
plt.title("Histogram Equalization")
plt.axis("off")

plt.subplot(2, 2, 4)
plt.imshow(clahe_image, cmap='gray')
plt.title("CLAHE")
plt.axis("off")

plt.tight_layout()
plt.show()

"""##### **9. Compare the effectiveness of Histogram Equalization and CLAHE for different types of images.**"""

# Comparing Histogram Equalization and CLAHE

plt.figure(figsize=(5, 4))

plt.subplot(1, 2, 1)
plt.imshow(hist_equalized, cmap='gray')
plt.title("Histogram Equalization")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(clahe_image, cmap='gray')
plt.title("CLAHE")
plt.axis("off")

plt.tight_layout()
plt.show()

# Saving all enhanced images

cv2.imwrite("contrast_stretched.jpg", contrast_stretched)
cv2.imwrite("histogram_equalized.jpg", hist_equalized)
cv2.imwrite("clahe_enhanced.jpg", clahe_image)

print("All enhanced images have been saved successfully.")
print("Files:")
print("1. contrast_stretched.jpg")
print("2. histogram_equalized.jpg")
print("3. clahe_enhanced.jpg")

"""##### **10. Document the observations and discuss the role of histogram-based enhancement in computer vision applications.**

# Answer:
## Observations

1. The original image may have low contrast, causing some objects and details to appear less visible.
2. The image histogram represents the distribution of pixel intensity values from 0 to 255.
3. A narrow histogram indicates that the image uses a limited range of intensity values and may have low contrast.
4. Contrast stretching expands the intensity range of the image and improves the overall contrast.
5. Histogram equalization redistributes pixel intensity values to improve the global contrast of the image.
6. Histogram equalization can make hidden details and edges more visible, but it may also amplify noise in some regions.
7. CLAHE performs contrast enhancement locally by dividing the image into small regions called tiles.
8. CLAHE uses a clip limit to prevent excessive contrast enhancement and reduce unnecessary noise amplification.
9. CLAHE generally provides better results than standard histogram equalization when the image has uneven illumination or important local details.
10. Histogram-based enhancement improves image visibility and makes important features such as edges, textures, and object boundaries easier to analyze.

## Significance in Computer Vision

Histogram-based image enhancement is an important preprocessing technique in computer vision. It improves the contrast and visibility of images before applying advanced operations such as feature extraction, image segmentation, object detection, classification, and recognition.

These techniques are commonly used in applications such as:

- Medical image analysis
- Satellite and remote sensing images
- Low-light image enhancement
- Face recognition
- Surveillance systems
- Industrial inspection
- Object detection
- Optical Character Recognition (OCR)
- Autonomous vehicles
- Robotics

Overall, histogram stretching, histogram equalization, and CLAHE help improve the quality of image data and can make subsequent computer vision tasks more reliable and effective.

# Questions and Answers

## 1. What is image contrast, and why is it important in image processing?

**Answer:**

Image contrast is the difference in intensity between the bright and dark regions of an image. A high-contrast image has clearly distinguishable bright and dark areas, while a low-contrast image has pixel intensities concentrated within a narrow range.

Contrast is important because it improves the visibility of objects, edges, textures, and other important features. Good contrast helps computer vision systems perform tasks such as image segmentation, feature extraction, object detection, and recognition more effectively.

---

## 2. Explain the concept of an image histogram. What information does it provide?

**Answer:**

An image histogram is a graphical representation of the distribution of pixel intensity values in an image.

For a grayscale image, the intensity values normally range from **0 to 255**, where:

- `0` represents black.
- `255` represents white.
- Values between 0 and 255 represent different shades of gray.

The **X-axis** of the histogram represents pixel intensity, while the **Y-axis** represents the number of pixels having that intensity.

A histogram provides information about the **brightness, contrast, and intensity distribution** of an image.

---

## 3. Differentiate between Histogram Stretching and Histogram Equalization.

**Answer:**

| Histogram Stretching | Histogram Equalization |
|---|---|
| Expands the existing intensity range. | Redistributes pixel intensities over a wider range. |
| Uses the minimum and maximum intensity values. | Uses the cumulative distribution function (CDF). |
| Generally preserves the overall shape of the histogram. | Attempts to produce a more uniformly distributed histogram. |
| It is a simpler enhancement technique. | It is a more powerful enhancement technique. |
| Suitable when the image uses only a small portion of the intensity range. | Suitable when pixel intensities are unevenly distributed. |

**In simple words:** Histogram stretching **expands** the intensity range, whereas histogram equalization **redistributes** the intensity values.

---

## 4. What is Contrast Limited Adaptive Histogram Equalization (CLAHE)? How does it differ from standard Histogram Equalization?

**Answer:**

CLAHE stands for **Contrast Limited Adaptive Histogram Equalization**. It is an improved version of histogram equalization that enhances contrast **locally** rather than applying the same transformation to the entire image.

The image is divided into small regions called **tiles**. Histogram equalization is performed independently on these regions. A **clip limit** is used to prevent excessive contrast enhancement and noise amplification.

The main difference is:

- **Standard Histogram Equalization:** Performs global contrast enhancement using the histogram of the entire image.
- **CLAHE:** Performs local contrast enhancement and limits excessive amplification of contrast.

Therefore, CLAHE is generally more effective for images with **uneven illumination and important local details**.

---

## 5. Why is histogram equalization commonly applied before feature extraction and image segmentation?

**Answer:**

Histogram equalization improves the contrast of an image and makes important features such as **edges, textures, boundaries, and objects** more visible.

Better contrast can make it easier for feature extraction algorithms to identify useful features. Similarly, segmentation algorithms can more easily distinguish between different regions when their intensity values are sufficiently separated.

Therefore, histogram equalization can improve the quality of the input image before subsequent computer vision operations.

---

## 6. Mention three real-world applications where histogram equalization is widely used.

**Answer:**

Three important applications are:

1. **Medical imaging** — enhancing X-rays, CT scans, MRI images, and other medical images.
2. **Satellite and remote sensing images** — improving the visibility of geographical features and terrain.
3. **Low-light photography and surveillance** — improving visibility in dark or poorly illuminated scenes.

Other applications include document processing, biometric systems, industrial inspection, and computer vision.

---

## 7. What are the limitations of global histogram equalization?

**Answer:**

The main limitations of global histogram equalization are:

1. It treats the **entire image as a single region**.
2. It may over-enhance some regions.
3. It can amplify **noise**, especially in relatively uniform areas.
4. It may produce unnatural-looking images.
5. It does not handle **uneven illumination** very effectively.
6. Important local details may not be enhanced properly.

CLAHE can overcome many of these limitations by performing local enhancement with a contrast limit.

---

## 8. How does contrast enhancement improve the performance of object detection and recognition systems?

**Answer:**

Contrast enhancement makes objects, edges, textures, and boundaries more distinguishable from their background.

This can help object detection and recognition systems by:

- Improving edge visibility.
- Making object boundaries clearer.
- Enhancing important visual features.
- Reducing the difficulty caused by poor illumination.
- Providing better-quality input to feature extraction and machine learning algorithms.

As a result, contrast enhancement can potentially improve the accuracy and robustness of computer vision systems, especially when the original image has poor contrast.

---

## 9. Compare histogram-based enhancement techniques with brightness adjustment methods.

**Answer:**

| Histogram-Based Enhancement | Brightness Adjustment |
|---|---|
| Changes the distribution of pixel intensities. | Mainly shifts pixel intensities brighter or darker. |
| Can improve contrast as well as visibility. | Primarily changes overall brightness. |
| Includes histogram stretching, equalization, and CLAHE. | Can be performed by adding or subtracting an intensity value. |
| Can reveal hidden details and improve local/global contrast. | May not improve the distinction between objects and background. |
| More useful for low-contrast images. | Useful when an image is simply too dark or too bright. |

For example, adding `30` to every pixel mainly increases brightness, whereas histogram equalization changes how the intensity values are distributed.

---

## 10. Why is CLAHE preferred for medical imaging and low-light image enhancement?

**Answer:**

CLAHE is preferred because it provides **local contrast enhancement** while limiting excessive amplification of noise.

Medical images and low-light images often contain:

- Uneven illumination.
- Low contrast.
- Small but important details.
- Noise.
- Regions with significantly different intensity levels.

Standard histogram equalization may enhance the entire image globally and can sometimes amplify noise or over-enhance certain regions. CLAHE processes smaller regions independently and uses a **clip limit** to control contrast enhancement.

Therefore, CLAHE can provide better visibility of local structures while reducing excessive contrast amplification, making it particularly useful for **medical imaging and low-light image enhancement**.
"""