# -*- coding: utf-8 -*-
"""Computer Vision Lab Sheet - 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15f6iIom5agmpd7yvESGGo-gcIoRfQD74

#### **Experiment No. 5**
#### **Experiment Name - Feature Extraction and Image Analysis using SIFT and HOG Descriptors**

#### **Steps**

##### **NAME : Atul Krishna**
##### **COURSE : B.Tech CSE**
##### **SECTION - B**
##### **SUBJECT : Computer Vision**
##### **ROLL NO. : 14**
##### **CU ID : CU24250231**

**1. Import the required libraries and load a real-world image or image dataset for analysis.**
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from skimage.feature import hog
from skimage import exposure
from google.colab import files

uploaded = files.upload()

image_name = list(uploaded.keys())[0]
image = cv2.imread(image_name)

image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

plt.figure(figsize=(4, 3))
plt.imshow(image_rgb)
plt.title("Original Image")
plt.axis("off")
plt.show()

"""**2. Convert the image into grayscale, if required, and perform basic preprocessing to improve image quality.**

"""

gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Resize image for easier processing
gray = cv2.resize(gray, (800, 1000))

plt.figure(figsize=(4, 3))
plt.imshow(gray, cmap="gray")
plt.title("Grayscale Image")
plt.axis("off")
plt.show()

"""**3. Apply the SIFT (Scale-Invariant Feature Transform) algorithm to detect keypoints and compute feature descriptors.**

"""

sift = cv2.SIFT_create()

keypoints, descriptors = sift.detectAndCompute(gray, None)

print("Number of SIFT Keypoints:", len(keypoints))
print("SIFT Descriptor Shape:", descriptors.shape if descriptors is not None else None)

"""**4. Visualize the detected keypoints on the image and analyze their distribution across different image regions.**"""

sift_image = cv2.drawKeypoints(
    gray,
    keypoints,
    None,
    flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS
)

plt.figure(figsize=(4, 3))
plt.imshow(sift_image, cmap="gray")
plt.title("SIFT Keypoints")
plt.axis("off")
plt.show()

"""**5. Extract Histogram of Oriented Gradients (HOG) features from the same image using appropriate parameters such as cell size, block size, and orientation bins.**"""

hog_features, hog_image = hog(
    gray,
    orientations=9,
    pixels_per_cell=(8, 8),
    cells_per_block=(2, 2),
    visualize=True
)

print("Number of HOG Features:", len(hog_features))
print("HOG Feature Shape:", hog_features.shape)

"""**6. Visualize the HOG descriptor to understand the gradient orientation patterns captured from the image.**"""

hog_image_rescaled = exposure.rescale_intensity(
    hog_image,
    in_range=(0, 10)
)

plt.figure(figsize=(4, 3))
plt.imshow(hog_image_rescaled, cmap="gray")
plt.title("HOG Visualization")
plt.axis("off")
plt.show()

"""**7. Compare the characteristics of SIFT keypoints and HOG descriptors with respect to scale invariance, rotation invariance, and computational efficiency.**

| Feature | SIFT | HOG |
|---|---|---|
| Full Form | Scale-Invariant Feature Transform | Histogram of Oriented Gradients |
| Feature Type | Local feature descriptor | Shape and edge descriptor |
| Scale Invariance | Yes | No |
| Rotation Invariance | Yes | Limited |
| Illumination Robustness | Good | Moderate |
| Feature Representation | Keypoints and descriptors | Gradient orientation histograms |
| Computational Complexity | Relatively higher | Relatively lower |
| Main Applications | Image matching, object recognition, image stitching | Object detection, pedestrian detection, shape recognition |

### Analysis

- **SIFT** detects distinctive keypoints in an image and generates descriptors that are robust to changes in **scale and rotation**.
- **HOG** represents an image using the **distribution of gradient orientations**, mainly capturing edges, shapes, and object structure.
- SIFT is more suitable for **image matching and object recognition** where scale and rotation changes are expected.
- HOG is more suitable for **shape-based object detection and classification**.
- SIFT generally requires more computational resources than HOG.

### Conclusion

SIFT and HOG are effective feature extraction techniques, but their suitability depends on the application. **SIFT is preferred for local feature matching and recognition, while HOG is preferred for shape and edge-based object detection.**

**8. Apply SIFT or HOG features to perform basic image matching or object recognition using two similar images.**
"""

print("Uploaded a second similar image:")

uploaded2 = files.upload()

image2_name = list(uploaded2.keys())[0]
image2 = cv2.imread(image2_name)

gray2 = cv2.cvtColor(image2, cv2.COLOR_BGR2GRAY)
gray2 = cv2.resize(gray2, (500, 500))

# Detect SIFT features in second image
keypoints2, descriptors2 = sift.detectAndCompute(gray2, None)

# Create matcher
bf = cv2.BFMatcher()

matches = bf.knnMatch(descriptors, descriptors2, k=2)

# Apply Lowe's ratio test
good_matches = []

for m, n in matches:
    if m.distance < 0.75 * n.distance:
        good_matches.append(m)

print("Total matches:", len(matches))
print("Good matches:", len(good_matches))

match_image = cv2.drawMatches(
    gray,
    keypoints,
    gray2,
    keypoints2,
    good_matches,
    None,
    flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS
)

plt.figure(figsize=(10, 8))
plt.imshow(match_image, cmap="gray")
plt.title("SIFT Image Matching")
plt.axis("off")
plt.show()

"""**9. Evaluate the strengths and limitations of both feature extraction techniques for different computer vision tasks.**
### SIFT Evaluation

* SIFT provides robust feature detection and description.
* It is invariant to changes in **scale and rotation**.
* It is suitable for **image matching and object recognition**.
* The number of good matches can be used to measure the similarity between two images.

### HOG Evaluation

* HOG captures the **shape and edge information** of an image.
* It represents an image using the distribution of **gradient orientations**.
* It is useful for **object detection and classification**.
* HOG is computationally simpler than SIFT but is less robust to scale and rotation changes.

### Strengths and Limitations

| Technique | Strengths                                                     | Limitations                                         |
| --------- | ------------------------------------------------------------- | --------------------------------------------------- |
| SIFT      | Scale and rotation invariant, robust feature matching         | Computationally more expensive                      |
| HOG       | Good shape and edge representation, computationally efficient | Sensitive to scale, rotation, and viewpoint changes |

### Observation

SIFT performs better for **local feature matching and object recognition**, whereas HOG is more suitable for **shape-based object detection and classification**.

**10. Document the observations and discuss suitable applications where SIFT and HOG descriptors can be effectively utilized.**
### Observations

* SIFT successfully detected important **keypoints** from the image and generated feature descriptors.
* SIFT features were useful for identifying similar regions between two images.
* HOG extracted **gradient and edge information** and represented the shape and structure of the image.
* SIFT showed better robustness to **scale and rotation changes**.
* HOG provided an efficient representation of **object shape and edges**.
* SIFT required comparatively more computational resources, while HOG was relatively simpler and faster.

### Applications
**SIFT:**

* Image matching
* Object recognition
* Image stitching
* Image registration
* Object tracking

**HOG:**

* Object detection
* Pedestrian detection
* Shape recognition
* Image classification
* Human detection
### Conclusion

SIFT and HOG are effective feature extraction techniques used in computer vision. **SIFT is more suitable for local feature matching and object recognition**, while **HOG is more suitable for shape and edge-based object detection and classification**.

# Questions and Answers

#### 1. What is feature extraction, and why is it important in computer vision?

Feature extraction is the process of identifying important and meaningful information from an image, such as **edges, corners, shapes, textures, and keypoints**.

It is important because it converts raw image data into useful features that can be used for **image classification, object recognition, image matching, and detection**.

#### 2. Explain the working principle of Scale-Invariant Feature Transform (SIFT).

SIFT detects distinctive keypoints in an image and generates feature descriptors for them.

The main steps of SIFT are:

1. **Scale-space construction** — images are analyzed at different scales.
2. **Keypoint detection** — important points are identified using Difference of Gaussian (DoG).
3. **Keypoint localization** — unstable or low-contrast points are removed.
4. **Orientation assignment** — an orientation is assigned to each keypoint.
5. **Descriptor generation** — a numerical descriptor is created for each keypoint.

These descriptors can then be compared between images for **image matching and object recognition**.

#### 3. What are keypoints and feature descriptors in image analysis?

**Keypoints** are distinctive points in an image, such as **corners, edges, or regions with significant intensity changes**, that can be reliably detected.

**Feature descriptors** are numerical representations of the region around a keypoint. They describe the important properties of that region and are used for **matching similar features between images**.

For example, SIFT detects keypoints and generates a **128-dimensional descriptor** for each keypoint.

#### 4. Explain the concept of Histogram of Oriented Gradients (HOG) and its significance.

HOG is a feature extraction technique that represents an image using the **distribution of gradient directions or orientations**.

The image is divided into small cells, and the gradients in each cell are calculated. These gradients are grouped into orientation bins to form histograms. The histograms are then normalized over blocks.

HOG is significant because it effectively captures the **shape, edges, and structure of objects** and is commonly used for **object and pedestrian detection**.

#### 5. Compare SIFT and HOG based on robustness, computational complexity, and practical applications.

| Feature                  | SIFT                                                | HOG                                                    |
| ------------------------ | --------------------------------------------------- | ------------------------------------------------------ |
| Robustness               | Robust to scale and rotation changes                | Mainly robust to small changes in illumination         |
| Scale Invariance         | Yes                                                 | No                                                     |
| Rotation Invariance      | Yes                                                 | Limited                                                |
| Computational Complexity | Relatively higher                                   | Relatively lower                                       |
| Feature Type             | Local features                                      | Shape and edge features                                |
| Applications             | Image matching, object recognition, image stitching | Object detection, pedestrian detection, classification |

**Conclusion:** SIFT is more suitable for **image matching**, while HOG is more suitable for **shape-based object detection**.

#### 6. Why is SIFT considered invariant to scale and rotation?

SIFT is considered **scale invariant** because it detects keypoints at different image scales using a scale-space representation.

It is considered **rotation invariant** because an orientation is assigned to each keypoint based on the local gradient directions. The descriptor is then generated relative to this orientation.

Therefore, the same feature can be recognized even when the image is **resized or rotated**.

#### 7. Mention three real-world applications where HOG descriptors are commonly used.

Three common applications of HOG are:

1. **Pedestrian detection** in surveillance and traffic systems.
2. **Human detection** in images and videos.
3. **Object detection and classification** in computer vision systems.

#### 8. Why is feature extraction performed before image classification or object detection?

Feature extraction is performed to convert raw image data into **meaningful and compact information** such as edges, shapes, textures, and keypoints.

This makes it easier for a classification or detection algorithm to identify patterns in the image, reduces unnecessary data, and can improve **computational efficiency and accuracy**.

#### 9. What are the advantages and limitations of handcrafted feature descriptors compared to deep learning-based feature extraction?

##### Advantages of Handcrafted Features

* Simple to understand and implement.
* Require less computational power.
* Can work well with smaller datasets.
* Features such as edges and shapes are explicitly defined.

##### Limitations of Handcrafted Features

* Performance depends on manually designed features.
* May not handle complex variations effectively.
* Usually less flexible than deep learning methods.
* May perform poorly on highly complex image recognition tasks.

##### Deep Learning

Deep learning models such as **Convolutional Neural Networks (CNNs)** automatically learn useful features from images and generally perform better on large and complex datasets, but they usually require **more data and computational resources**.

#### 10. How do feature extraction techniques contribute to image matching, face recognition, and object detection systems?

Feature extraction techniques convert images into **meaningful numerical representations** that can be compared or classified.

* **Image Matching:** SIFT features can be extracted from two images and matched to identify similar regions.
* **Face Recognition:** Important facial features such as edges, shapes, and local patterns can be extracted and compared.
* **Object Detection:** HOG can represent the shape and edges of objects, helping detection algorithms identify objects such as humans or vehicles.

Therefore, feature extraction provides the **important visual information required by computer vision systems** for recognition, matching, and detection.
"""